### ISSUE TITLE
Returns 502 when creating a snapshot

### ISSUE THREAD

**Issue by scoful** [mekarpeles/api.archive.org#24]
as the title says
![image](https://github.com/ArchiveLabs/api.archivelab.org/assets/12808733/595b48ee-1d8c-43c3-af42-a6f570db7aa1)

**Comment by mekarpeles** [comment]
Hi, it's possible the service is not operational, I haven't been maintaining it and I suggest using the standard Save Page Now APIs offered by the Wayback Machine.

**Comment by scoful** [comment]
> Hi, it's possible the service is not operational, I haven't been maintaining it and I suggest using the standard Save Page Now APIs offered by the Wayback Machine.

What is the documentation address for the standard api?
